server:
  port: 9292
spring:
  application:
    name: auth-client
  cloud:
    kubernetes:
      enabled: false
springfox.documentation.swagger.v2:
  path: /api/v1/auth-client/api-doc
logging:
  level:
    com.agenatech: DEBUG
